---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echov5-dev
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.4
spec:
  releaseName: echov5-prod
  chart:
    git: git@github.com:Whitehawk2/HelmCharts
    path: CD/Charts/echo
    ref: master
  values:
    image:
      # repository: stefanprodan/podinfo
      repository: eu.gcr.io/theta-era-322507/echov5
      tag: 0.4.11
    replicaCount: 2
    hpa:
      enabled: false
