---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echov5-rc
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: echov5-rc
  chart:
    git: git@github.com:Whitehawk2/HelmCharts
    path: CD/Charts/echo
    ref: master
  values:
    image:
      # repository: stefanprodan/podinfo
      repository: eu.gcr.io/theta-era-322507/echov5
      tag: stg-3jnc8syt
    replicaCount: 2
    hpa:
      enabled: false
